[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
local_net=172.31.32.0/20
external_media_address=16.192.71.227
external_signaling_address=16.192.71.227

[200]
type=endpoint
context=internal
disallow=all
allow=ulaw
auth=200
aors=200

[200]
type=auth
auth_type=userpass
password=unsecurepassword
username=200

[200]
type=aor
max_contacts=1

[201]
type=endpoint
context=internal
disallow=all
allow=ulaw
auth=201
aors=201

[201]
type=auth
auth_type=userpass
password=unsecurepassword
username=201

[201]
type=aor
max_contacts=1

[202]
type=endpoint
context=internal
disallow=all
allow=ulaw
auth=202
aors=202

[202]
type=auth
auth_type=userpass
password=unsecurepassword
username=202

[202]
type=aor
max_contacts=1

[203]
type=endpoint
context=internal
disallow=all
allow=ulaw
auth=203
aors=203

[203]
type=auth
auth_type=userpass
password=unsecurepassword
username=203

[203]
type=aor
max_contacts=1