[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

[200]
type=endpoint
context=from-internal
disallow=all
allow=ulaw
auth=200
aors=200

[200]
type=auth
auth_type=userpass
password=unsecurepassword
username=200

[200]
type=aor
max_contacts=1

[201]
type=endpoint
context=from-internal
disallow=all
allow=ulaw
auth=201
aors=201

[201]
type=auth
auth_type=userpass
password=unsecurepassword
username=201

[201]
type=aor
max_contacts=1

[202]
type=endpoint
context=from-internal
disallow=all
allow=ulaw
auth=202
aors=202

[202]
type=auth
auth_type=userpass
password=unsecurepassword
username=202

[202]
type=aor
max_contacts=1

[203]
type=endpoint
context=from-internal
disallow=all
allow=ulaw
auth=201
aors=201

[203]
type=auth
auth_type=userpass
password=unsecurepassword
username=201

[203]
type=aor
max_contacts=1
