; voicemail.conf
[general]
format=wav49|gsm|wav
serveremail=asterisk@localhost
attach=yes
maxmsg=100
maxsecs=180
minsecs=3
maxsilence=10
silencethreshold=128
sendvoicemail=yes

[default]
200 => 1234,LEON ARDAVINCI,leon@atelier.local
201 => 1234,PAUL PICASSO,paul@atelier.local
202 => 1234,MICKAEL ANGELO,mickael@atelier.local
203 => 1234,SALVATORE DALIDA,salvatore@atelier.local